/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGNMENT_H_RPCGEN
#define _ASSIGNMENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ASSIGNMENT 0x20000001
#define ASSIGNMENTVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define MYASSIGNMENT 1
extern  int * myassignment_1(char **, CLIENT *);
extern  int * myassignment_1_svc(char **, struct svc_req *);
extern int assignment_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MYASSIGNMENT 1
extern  int * myassignment_1();
extern  int * myassignment_1_svc();
extern int assignment_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OS_H_RPCGEN */
